sudo: required

language: scala

services:
- docker

before_install:
- docker pull hseeberger/scala-sbt

script:
- docker run --rm -v $(pwd):/app -w /app hseeberger/scala-sbt bash -c "sbt sbt-version"
- docker run --rm -v $(pwd):/app -w /app hseeberger/scala-sbt bash -c "sbt clean test"
