version: 2
jobs:
  test:
    docker:
    - image: hseeberger/scala-sbt:latest
    steps:
    - checkout
    - run: sbt sbt-version
    - run: sbt clean test

workflows:
  version: 2
  build_and_test:
    jobs:
    - test
